### ISSUE TITLE
gtsd.label

### ISSUE THREAD

**Issue by Deltaidiots** [xfqbuaa/Traffic-Signs-Detect-German#4]
I can't able to find this file but it is mentioned in code how can I generate this?
To generate record files we need this file. 

help needed

**Comment by xfqbuaa** [comment]
This file you need to transfer it from GTSDB label file using python scripts, just some format transformation. 
The format you can follow tensorflow record requirement. 
long time ago project, I can not provide detail file to you now.

**Comment by Mehran970** [comment]
Hi. go to [here](https://drive.google.com/file/d/1hKdjTsiFm_vdtZPdto0QJihThGFOPEkq/view).
